name: .NET Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Release]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore \RepoITS\ConsoleApptest\ConsoleApptest.sln

    - name: Build solution
      run: dotnet build \RepoITS\ConsoleApptest\ConsoleApptest.sln --configuration ${{ matrix.configuration }} --no-restore

    - name: Run tests
      run: dotnet test \RepoITS\ConsoleApptest\ConsoleApptest.sln --configuration ${{ matrix.configuration }} --no-build
